name: dsystem
description: "A Sample design system"
version: 0.0.1
homepage: "A simple design system created for ds"

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

publish:
  github:
    token: # Replace with your token (not shown here)
    owner: Raks-Javac
    repo: testing_t
